import io

from pptx import Presentation

from backend.features import docgen


def _texts(slide):
    return "\n".join(shape.text for shape in slide.shapes if hasattr(shape, "text") and shape.text)


def test_structured_pptx_uses_designed_widescreen_deck():
    spec = {
        "title": "Planet Earth",
        "subtitle": "A concise science deck",
        "slides": [
            {
                "title": "Earth at a glance",
                "bullets": [
                    "Third planet from the Sun",
                    "Only known world with surface oceans",
                    "Dynamic atmosphere and climate",
                ],
                "notes": "Open with scale and habitability.",
            },
            {
                "title": "Why it matters",
                "bullets": ["Supports life", "Shapes weather", "Records geologic history"],
            },
        ],
    }

    result = docgen.render_spec("Planet Earth", "claude_plan/opus", spec, "pptx")
    prs = Presentation(io.BytesIO(result.content))

    assert result.filename.endswith(".pptx")
    assert prs.slide_width > prs.slide_height
    assert len(prs.slides) == 3
    assert "Planet Earth" in _texts(prs.slides[0])
    assert "Generated by Orrery" in _texts(prs.slides[0])
    assert "Earth at a glance" in _texts(prs.slides[1])
    assert "Third planet from the Sun" in _texts(prs.slides[1])
    assert prs.slides[1].notes_slide.notes_text_frame.text == "Open with scale and habitability."
